name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: build
      run: mkdir build && cd build
    - name: generate cmake file
      run: cmake ..
    - name: build
      run: cmake --build .
